### ISSUE TITLE
Help Guys

### ISSUE THREAD

**Issue by pulliam** [pulliam/shylock_pulliam#2]
Since I lost class yesterday, I'm trying to catch up to JQuery today. 
I started with this code I just pushed. 
I know there is something I'm doing wrong but not quite sure what.
<li> .val() gets the value of the input right? 

thanks
<li> [code](https://github.com/pulliam/shylock_pulliam/commit/cc3fc2f003eb00a848035a304df9a3958c5a5db8)

**Comment by pulliam** [comment]
@sungchoi I did some changes. I think I still don't know what Im doing wrong... 
[second_edit](https://github.com/pulliam/shylock_pulliam/commit/21e708529ce393f48698731fc565b9f529eea282)

**Comment by pulliam** [comment]
[third_edit](https://github.com/pulliam/shylock_pulliam/commit/cc3fc2f003eb00a848035a304df9a3958c5a5db8)

**Comment by sungchoi** [comment]
Yes. jQueryObject#val() gives back the value if that element type has a value property.

If you are having problems, you may need to do

``` js
var newValue = $('#prompt').eq(0).val();
```

in order to call `val` only on the first element of the collection.
Make sure the input actually has a value and test all of your assumptions.
