### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by pulliam** [pulliam/shylock_pulliam#3]
Hey, I just fixed the problem. 
Im confused with the next step of the lab. Not sure what I need to do... 

"Create each < li > with one of three possible classes:
command : The command from the prompt
action : Indicates actions performed by Shylock
quote : For things ShylockBot says"

**Comment by pulliam** [comment]
Can one of the instructors come help me? Im not sure I understand what Im supposed to do.

**Comment by sungchoi** [comment]
@pulliam 
Shylock's responses should be appended as <li> tags to ul#log.

Create each <li> with one of three possible classes:

command : The command from the prompt
action : Indicates actions performed by Shylock
quote : For things ShylockBot says

Create a list with three list items.
The first item has a class of command.
The second item has a class of action.
...

**Comment by pulliam** [comment]
Im still so confused.
