### ISSUE TITLE
I need help with the lab

### ISSUE THREAD

**Issue by pulliam** [pulliam/shylock_pulliam#4]
[last push](https://github.com/pulliam/shylock_pulliam/commit/7815898c5b8b32652ebe8fbc8a1327505d02f8db)

What do I do from here? It's very hard for me to understand what to do, I'm not sure if it's because I missed class yesterday? 
I'm very confused about how to proceed from here. 
So I understood you want 3 already pre-made on html < li > with command, action and quote. I did that and started sketching them into my main.js
I have no idea though how to know if what the person is typing is command action or quote, or how to get the number value from the input so I can calculate the numbers.... o.o 
Pls! help...

**Comment by sungchoi** [comment]
Hi Thais @pulliam ,

Check the README for this lab again. If you watch the GIF it should be more clear.

You want to get the value from the text input and then update the text for the list items based on the input text. I think you have it the other way around right now. 

Your jQuery is great. That's not the problem. In other words, you're fine with the material from yesterday.
You need to think through what the sequence of events should be.

**Comment by sungchoi** [comment]
@pulliam Pseudocode the problem and make sure to take your time.
