### ISSUE TITLE
So. Apaprently

### ISSUE THREAD

**Issue by pulliam** [pulliam/shylock_pulliam#5]
It's asking me to return something depending on what the user inputs. 
My pseudocode is this bellow. But honestly, is not taking me anywhere. I wish there was more guidance on the subject. I feel like someone that never heard of css before that has been asked to make a page colorful. :/ 

```
'purse' --->  'ShylockBot pulls out his purse containing ' + purseValue + ' ducats',
```

---

```
'loan' + person + Minusvalue + ' ducats' -----> 'ShylockBot gives Antonio ' + Minusvalue + ' ducats';
purseValue = purseValue - Minusvalue;
```

---

How Am I going to make this work for all values possibles? I can set a variable like my pseudocode MinusValue, but how can I scan for this value in the user input??????? Either I missed a week worth of class or Im ignorant because I don't feel like I have the tools to build this.

**Comment by sungchoi** [comment]
@pulliam 
No, you're not missing anything. 

Take a deep breath. Now think about how you would transform the string 'loan Antonio 500 ducats' into information you can use.

What are the other possible commands. Where in the string do they appear? What is the order of the other key words? Does the order ever change?

Send me your psuedocode.

**Comment by pulliam** [comment]
jQuery(document).ready(function( ){

var purseValue = 10000; //STARTS AT 10000
var $command = $('.command');
var $action = $('.action');
var $quote = $('.quote');

var options = {
    'purse': 'ShylockBot pulls out his purse containing ' + purseValue + ' ducats’,  
//THEY INPUT A PHRASE AND A NUMBER
// I NEED TO SOMEHOW GET ONLY THE NUMBER OUT OF THIS STRING
/ /I CANT TRY TO CONVERT STRING TO AN ARRAY AND FILTER BECAUSE THE NUMBER MIGHT HAVE MORE THAN 1 CHARACTER

## //ARRGG  I DONT KNOW HOW ELSE THAN

```
'loan' + person + Minusvalue + ' ducats': 'ShylockBot gives Antonio ' + Minusvalue + ' ducats';
purseValue = purseValue - Minusvalue;
```

//BUT, IF SOMEHOW I FIND OUT HOW TO GET THIS NUMBER, I PUT IT ON A VARIABLE CALLED MINUSVALUE AND SUBTRACT FROM PURSEVALUE THAT STARTS AT 10000

---

//conclusion…. 
Im very unmotivated. 

```
function filter (){
    if (typeOf this === number){
        return this;
    }
}
```

**Comment by sungchoi** [comment]
@pulliam Don't worry about the data type. Think about the order.
