### ISSUE TITLE
ShylockBot Doesn't know who he is landing money to.

### ISSUE THREAD

**Issue by pulliam** [pulliam/shylock_pulliam#6]
[last_commit](https://github.com/pulliam/shylock_pulliam/commit/770a037af6eb03e4d40f59221640c0d7a1855671)

So... This is a hard lab. 
I got the shylockbot to tell me the initial value of purse when I type "purse"
and to tell me how much money someone wants landed. But Im not sure how to scan for this person name........ 
Also, the variable for the shylockbot money gets stuck. I can keep using the keypress and it will give me accurate numbers Im typing but It wont calculate pursemoney - currenttyped money more than one time.
Help?

**Comment by sungchoi** [comment]
``` javascript
purseValue = (purseValue - subtractValue); //This Part is getting stuck on the first defined value.
```

When you say 'This Part is getting stuck on the first defined value.', do you mean that the purseValue gets reset each time back to 10000? Why do you think that is? Where is it being defined?

**Comment by pulliam** [comment]
https://github.com/pulliam/shylock_pulliam

Take a look at it. When I try on console, purseValue is not defined. Ive tried inside or outside the function.... 
And it doesn't get redefined actually. It stops after the first definition:

> > purseValue = 10000;
> > lands 50 dolars (first time I input)
> >  purseValue = 9950  (from 10000)
> > lands 50 dolars  (second time I input )
> >  purseValue = 9950

**Comment by pulliam** [comment]
Hey! I got it to keep track (purseValue). But for some reason on the console it says its undefined....

**Comment by pulliam** [comment]
Check It out:

jQuery(document).ready(function(){
<b>var allLoans = [];</b>
var purseValue = 10000;

$('#prompt').keypress(function() {
    var whatMyUserTyped = $('#prompt').val();
    if (event.keyCode == 13) {
        if (whatMyUserTyped === 'purse'){
            $('#log li:last').text('ShylockBot pulls out his purse containing '+ purseValue+ ' ducats');  
        } else {
            this.subtractValue = subtractValue;
            var subtractValue = parseInt(whatMyUserTyped.match(/\d+/));
            purseValue = (purseValue - subtractValue); 
            $('#log li:last').text('ShylockBot gives SOMEONE '+ subtractValue + ' ducats');
            <b>allLoans = allLoans.push(subtractValue);</b>
        }
    }
});

});

```
```

**Comment by pulliam** [comment]
It states allLoans.push is not a function....
